#!/usr/bin/env rake
begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end
begin
  require 'rdoc/task'
rescue LoadError
  require 'rdoc/rdoc'
  require 'rake/rdoctask'
  RDoc::Task = Rake::RDocTask
end

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'EachBatched'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('lib/**/*.rb')
end



Bundler::GemHelper.install_tasks

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = false
end

begin
  require 'simplecov'
rescue LoadError
  puts 'WARNING: missing simplecov library, some tasks are not available'
else
  desc 'Analyze code coverage with tests'
  task :coverage => 'coverage:clobber' do
    ENV['USE_SIMPLECOV'] = :true.to_s
    Rake::Task['test'].invoke
    # see top of test helper for the rest of this task, which is triggered with the environment var....
  end
  namespace :coverage do
    desc 'Remove output directory generated by simplecov'
    task :clobber do
      FileUtils.rm_rf(File.expand_path('../coverage', __FILE__))
    end
  end
end

task :default => :test
